name: <%= @settings["name"] ? @settings["name"] : "Shell" %>
root: <%= @settings["root"] ? @settings["root"] : "~" %>

windows:
    - <%= @settings["name"] ? @settings["name"] : "Shell" %>:
        panes:
            -
            -
            -
            -
